# Generated by Django 5.2 on 2025-05-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_class_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
